name: Run Rake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Specify your Ruby version here

    - name: Install dependencies
      env:
        BUNDLE_PATH: vendor/bundle
      run: |
        bundle config set --local path 'vendor/bundle'
        gem install bundler
        bundle install

    - name: Run Rake tasks
      run: rake
