name: Run Rake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'

    steps:
    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1' # Specify your Ruby version here
        bundler-cache: true

    - name: Install dependencies
      env:
        BUNDLE_PATH: vendor/bundle
      run: |
        bundle config set --local path 'vendor/bundle'
        gem install bundler
        bundle install

    - name: Run Rake tasks
      run: bundle exec rake
